baseURL = 'https://oloke.xyz/'
languageCode = 'en-us'
title = 'oloke.xyz'
theme = 'oloke-theme'

[params]
  author = 'Aleksander Błażelonis'
  description = "2nd year Teleinformatics student"
  interests = ['Linux System Administration', 'Virtualization', 'Media compression', 'Networking', 'Cybersecurity']
  technologies = ['Proxmox - Single node and cluster with HA storage', 'OpenWrt - My goto router operating system', 'Docker - For many containers in my HomeLab', 'Linux - Both on server and desktop', 'Tor - I was a relay operator at some point', 'OPNSense - Still learning', 'Git, SSH, WireGuard, FFmpeg, Ansible, Wireshark', 'Python, C/C++, Bash, Go, Javascript']

[markup.highlight]
  codeFences = true
  guessSyntax = true
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  tabWidth = 2
  noClasses = false

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 3
  [[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4
  [[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
